### ISSUE TITLE
Playing the song losses selection marker

### ISSUE THREAD

**Issue by 32leaves** [bwl21/zupfnoter#191]
# Steps to reproduce
1. Select a note in the tunes/sore sheet.
2. Hit the play button and wait for the red selection box to move away from the original selection.
3. Hit the stop button

# Expected behavior
The red selection box should return to the formerly selected note.

# Observed behavior
The red selection box disappears entirely. The formerly selected note remains selected, as confirmed by clicking on "Play" which starts to play from the very same note.

# Misc.
- Tested in Firefox Quantum 57.0 on Windows 10

**Comment by bwl21** [comment]
Thanks for the report. This will be fixed as a side effect of #126 which integrates a new player.
I also integrate two different hilihghts, one for select and one for playing. The playing one is blue and no longer interferes with the selection highlighting.
